apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-test
  strategy: {}
  template:
    metadata:
      labels:
        app: stream-test
    spec:
      containers:
        - image: 127.0.0.1:5000/stream-test:local
          name: main
